### ISSUE TITLE
Game crashes on credits screen

### ISSUE THREAD

**Issue by Invictaz** [riperiperi/FreeSO#101]
When clicking the top left icon (marked with the black arrow) in the select a sim screen it should display the credits. These are empty. When trying to exit this screen the following error occurs.

![crashfreeso](https://user-images.githubusercontent.com/20338545/37314890-881114a8-264e-11e8-96e3-b856cf8e7a06.png)

**Comment by riperiperi** [comment]
The credits have now been disabled until they are fully implemented. They've kind of been in this state for 3 years.
