### ISSUE TITLE
Game crashes on "kickmeout" command in Sandbox mode

### ISSUE THREAD

**Issue by Invictaz** [riperiperi/FreeSO#102]
Select "kickmeout" as action for a Sim and the game crashes in Sandbox mode

![crash](https://user-images.githubusercontent.com/20338545/37633112-05a0bf32-2be9-11e8-9432-7e9da5142620.png)

**Comment by riperiperi** [comment]
Rather unusual, since that implies the avatar it tried to run the interaction on did not have an associated thread. Next version should handle this case.
