### ISSUE TITLE
Build FreeSO for Android

### ISSUE THREAD

**Issue by Flone-dnb** [riperiperi/FreeSO#179]
I'm trying to build FreeSO for Android using VS 2017 (Windows). So I choose "Release, Any CPU, FSODroid", I'm I doing it right? I got 33 errors. Any tips, please?

```
The type or namespace name 'FSO' could not be found (are you missing a using directive or an assembly reference?)

The type or namespace name 'TargalmagePCL' could not be found (are you missing a using directive or an assembly reference?)

The name 'FSOEnvironment' does not exist in the current context
```
And some other errors... (all in FSOActivity.cs)

**Comment by Flone-dnb** [comment]
I don't know, tried VS2015, Monogame 3.5 and Xamarin installed but still getting a lot of errors.

**Comment by hello-wahyu** [comment]
This might help: https://stackoverflow.com/questions/4764978/the-type-or-namespace-name-could-not-be-found
