### ISSUE TITLE
[UI] Replace SpriteFont rendering with C# managed FreeType alternative

### ISSUE THREAD

**Issue by riperiperi** [riperiperi/FreeSO#22]
Currently, the game renders text using XNA SpriteFonts generated from the game's fonts at compile time. Not only does this mean we're distributing a rendered version of the game font, but it means that the result is rather low quality (limited size range) and requires slow redraws every frame.

We should be rendering using the ttf font directly, into "label" textures that are only regenerated when the text is changed. 

We need a library that does this entirely within C#, so that we can cross compile to ARM easily. That means no wrapper classes!

**Comment by jackmawer** [comment]
SharpFont is a widely adopted, cross-platform library for this exact purpose - it's MIT licensed, so it gives some decent freedoms, and it's available through NuGet.

**Comment by RHY3756547** [comment]
Yes, I too have googled "c# freetype alternative". These are FreeType bindings, which are useless on iOS/Android without a matching ARM version of FreeType linked in.

**Comment by agthrs** [comment]
Is ARM support still required considering the circumstances?

**Comment by riperiperi** [comment]
We have went with a (multi-)signed distance field font generated from the TTF. This is still a spritefont but the level of control means that we can support multiple atlases, for optional character packs like japanese. We are still limited to the characters that the SimDialogue ttf includes - to extend that set I recommend editing the font with the free application "FontForge". This has already been done to modify kerning on some characters - more information on this will be added to the forums soon.
