### ISSUE TITLE
I implemented a register dialog for FreeSO

### ISSUE THREAD

**Issue by ghost** [riperiperi/FreeSO#274]
Hello my name it's Isaac and i implemented a register dialog in the login screen. I'am beginner programmer.
![Captura de pantalla 2023-11-12 160107](https://github.com/riperiperi/FreeSO/assets/80901734/76cc1411-3b16-4eab-a0ac-7ddeab72285c)

I cloned FreeSO for make this I hope it's not a bother

**Comment by riperiperi** [comment]
This might be useful, assuming it's just a wrapper around the `beta.freeso.org` registration API. Though it would need UI work to look consistent with other dialogs and explain what each of the fields is and why it's required.

**Comment by hhk02** [comment]
True, I forgot to mention that it is each thing, the first field would be the username, the second, as you may have deduced, would be the email field and the last field would be the password. As for the code, it makes an HTTP POST to the server that is on the game configuration specifically GameEntryUrl the code adds /userapi/registration at the end. I think it could be necessary in the hypothetical case that the beta.freeso.org page was down and thus I would have another exit. I'm currently learning how to do the dialogues so it looks so simple.

**Comment by hhk02** [comment]
I work to make this more better

**Comment by hhk02** [comment]
UPDATE:
![imagen](https://github.com/riperiperi/FreeSO/assets/80901734/b97f4305-7974-4481-b9ab-4f00ff5b2b1f)
