### ISSUE TITLE
Bring back LAN option

### ISSUE THREAD

**Issue by Invictaz** [riperiperi/FreeSO#73]
In builds before 398 (http://forum.freeso.org/threads/creating-lan-server.2495/) there was the option to join a LAN server. In the newest builds (with master server) such an option does not exist.
Can we expect it back in the near future?

**Comment by RHY3756547** [comment]
The very near future, yes. This is partially working on my local copy of FreeSO.

**Comment by riperiperi** [comment]
Sandbox mode is now in current master.
