### ISSUE TITLE
Bigger UI on high resolutions

### ISSUE THREAD

**Issue by Invictaz** [riperiperi/FreeSO#74]
The UI isn't exactly very big on high resolutions (1080P). Is there an option to increase the icon / font size?

Simitone seems an option but I am unaware how to set that up without owning The Sims Collection.

**Comment by RHY3756547** [comment]
UI Scaling was partially implemented for the mobile version of FreeSO that was scrapped. Someone could still extend it to work on desktop, though I'm probably not going to do this.

**Comment by Invictaz** [comment]
Has DPI scaling now since build 60, needs 125% DPI also

**Comment by riperiperi** [comment]
Will do, but non integral scales have issues with many UI elements (typically 9 slice). It's probably an issue of floor vs ceiling for positions and sizes.

**Comment by riperiperi** [comment]
This is now complete. There's a small bug with starting the game where you have to resize the window to fix ui layout, but it works apart from that.
